services:
  - type: web
    name: virtual-altar-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: REACT_APP_API_BASE_URL
        sync: false
      - key: REACT_APP_FRONTEND_URL
        sync: false
      - key: REACT_APP_ENABLE_PREMIUM
        value: true
      - key: REACT_APP_ENABLE_SHARING
        value: true
      - key: REACT_APP_ENABLE_UPLOADS
        value: true
      - key: REACT_APP_DEFAULT_WALL_HEIGHT
        value: 600
      - key: REACT_APP_DEFAULT_WALL_WIDTH
        value: 900
      - key: REACT_APP_DEFAULT_WALL_COLOR
        value: '#f4f4f4'
      - key: REACT_APP_DEFAULT_BORDER_STYLE
        value: solid
      - key: REACT_APP_MONTHLY_PRICE
        value: 20
      - key: REACT_APP_SIX_MONTHS_PRICE
        value: 100
      - key: REACT_APP_ANNUAL_PRICE
        value: 180 