services:
  - type: web
    name: virtual-altar
    env: node
    plan: free
    buildCommand: cd backend && npm install && cd ../my_app && npm install && npm run build && cd ../backend
    startCommand: cd backend && npm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: 3306
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: UPLOAD_PATH
        value: uploads
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: MONTHLY_PRICE
        value: 20
      - key: SIX_MONTHS_PRICE
        value: 100
      - key: ANNUAL_PRICE
        value: 180 