services:
  - type: web
    name: virtual-altar
    env: node
    plan: free
    buildCommand: cd backend && npm install && cd ../my_app && npm install && npm run build && cd ../backend
    startCommand: cd backend && npm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: 3306
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: UPLOAD_PATH
        value: uploads
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: MONTHLY_PRICE
        value: 20
      - key: SIX_MONTHS_PRICE
        value: 100
      - key: ANNUAL_PRICE
        value: 180
      - key: REACT_APP_ENABLE_PREMIUM
        value: true
      - key: REACT_APP_ENABLE_SHARING
        value: true
      - key: REACT_APP_ENABLE_UPLOADS
        value: true
      - key: REACT_APP_DEFAULT_WALL_HEIGHT
        value: 600
      - key: REACT_APP_DEFAULT_WALL_WIDTH
        value: 900
      - key: REACT_APP_DEFAULT_WALL_COLOR
        value: "#f4f4f4"
      - key: REACT_APP_DEFAULT_BORDER_STYLE
        value: solid
      - key: REACT_APP_MONTHLY_PRICE
        value: 20
      - key: REACT_APP_SIX_MONTHS_PRICE
        value: 100
      - key: REACT_APP_ANNUAL_PRICE
        value: 180 